apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-cloning
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-csi-storage
  dataSource:
    kind: PersistentVolumeClaim
    name: pvc-nfs