apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-snapshot-restored
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-csi-storage
  dataSource:
    name: pvc-nfs-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io